export const PERMISSIONS = {
  LOGIN: 'LOGIN', TICKET_CREATE: 'TICKET_CREATE', TICKET_VIEW_OWN: 'TICKET_VIEW_OWN', TICKET_VIEW_ALL: 'TICKET_VIEW_ALL',
  TICKET_EDIT_OWN: 'TICKET_EDIT_OWN', TICKET_STATUS_CHANGE: 'TICKET_STATUS_CHANGE', TICKET_ASSIGN: 'TICKET_ASSIGN',
  TICKET_REASSIGN: 'TICKET_REASSIGN', TICKET_ESCALATE: 'TICKET_ESCALATE', COMMENT_PUBLIC: 'COMMENT_PUBLIC',
  COMMENT_INTERNAL: 'COMMENT_INTERNAL', ATTACHMENT_UPLOAD: 'ATTACHMENT_UPLOAD', CATEGORY_MANAGE: 'CATEGORY_MANAGE',
  PRIORITY_MANAGE: 'PRIORITY_MANAGE', SLA_MANAGE: 'SLA_MANAGE', USER_MANAGE: 'USER_MANAGE', DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  DASHBOARD_VIEW_LIMITED: 'DASHBOARD_VIEW_LIMITED', REPORT_VIEW: 'REPORT_VIEW', REPORT_VIEW_LIMITED: 'REPORT_VIEW_LIMITED',
  SURVEY_RESPOND: 'SURVEY_RESPOND', KNOWLEDGE_MANAGE: 'KNOWLEDGE_MANAGE',
  CRM_CLIENT_VIEW: 'CRM_CLIENT_VIEW', CRM_CLIENT_CREATE: 'CRM_CLIENT_CREATE', CRM_CLIENT_EDIT: 'CRM_CLIENT_EDIT',
  CRM_CONTACT_VIEW: 'CRM_CONTACT_VIEW', CRM_CONTACT_CREATE: 'CRM_CONTACT_CREATE', CRM_CONTACT_EDIT: 'CRM_CONTACT_EDIT',
  CRM_OPPORTUNITY_VIEW: 'CRM_OPPORTUNITY_VIEW', CRM_OPPORTUNITY_CREATE: 'CRM_OPPORTUNITY_CREATE', CRM_OPPORTUNITY_EDIT: 'CRM_OPPORTUNITY_EDIT',
  CRM_OPPORTUNITY_MOVE: 'CRM_OPPORTUNITY_MOVE', CRM_ACTIVITY_VIEW: 'CRM_ACTIVITY_VIEW', CRM_ACTIVITY_CREATE: 'CRM_ACTIVITY_CREATE',
  CRM_ACTIVITY_EDIT: 'CRM_ACTIVITY_EDIT', CRM_SURVEY_VIEW: 'CRM_SURVEY_VIEW', CRM_SURVEY_MANAGE: 'CRM_SURVEY_MANAGE',
  CRM_SURVEY_RESULTS: 'CRM_SURVEY_RESULTS', CRM_DASHBOARD: 'CRM_DASHBOARD', CRM_EXPORT: 'CRM_EXPORT', CRM_RESPONSE_VIEW: 'CRM_RESPONSE_VIEW',
} as const

const CRM_SALES = [
  PERMISSIONS.CRM_CLIENT_VIEW, PERMISSIONS.CRM_CLIENT_CREATE, PERMISSIONS.CRM_CLIENT_EDIT,
  PERMISSIONS.CRM_CONTACT_VIEW, PERMISSIONS.CRM_CONTACT_CREATE, PERMISSIONS.CRM_CONTACT_EDIT,
  PERMISSIONS.CRM_OPPORTUNITY_VIEW, PERMISSIONS.CRM_OPPORTUNITY_CREATE, PERMISSIONS.CRM_OPPORTUNITY_EDIT, PERMISSIONS.CRM_OPPORTUNITY_MOVE,
  PERMISSIONS.CRM_ACTIVITY_VIEW, PERMISSIONS.CRM_ACTIVITY_CREATE, PERMISSIONS.CRM_ACTIVITY_EDIT,
  PERMISSIONS.CRM_SURVEY_VIEW, PERMISSIONS.CRM_SURVEY_MANAGE, PERMISSIONS.CRM_SURVEY_RESULTS,
  PERMISSIONS.CRM_DASHBOARD, PERMISSIONS.CRM_EXPORT, PERMISSIONS.CRM_RESPONSE_VIEW,
] as const

const CRM_SUPERVISOR = [
  PERMISSIONS.CRM_CLIENT_VIEW, PERMISSIONS.CRM_CONTACT_VIEW, PERMISSIONS.CRM_OPPORTUNITY_VIEW, PERMISSIONS.CRM_ACTIVITY_VIEW,
  PERMISSIONS.CRM_SURVEY_VIEW, PERMISSIONS.CRM_SURVEY_RESULTS, PERMISSIONS.CRM_DASHBOARD, PERMISSIONS.CRM_EXPORT, PERMISSIONS.CRM_RESPONSE_VIEW,
] as const

const PORTAL = [PERMISSIONS.LOGIN, PERMISSIONS.TICKET_CREATE, PERMISSIONS.TICKET_VIEW_OWN, PERMISSIONS.TICKET_EDIT_OWN, PERMISSIONS.COMMENT_PUBLIC, PERMISSIONS.ATTACHMENT_UPLOAD, PERMISSIONS.SURVEY_RESPOND] as const

export const ROLE_PERMISSION_CODES = {
  ADMIN: Object.values(PERMISSIONS),
  SALES: [PERMISSIONS.LOGIN, ...CRM_SALES],
  SUPERVISOR: [PERMISSIONS.LOGIN, PERMISSIONS.TICKET_CREATE, PERMISSIONS.TICKET_VIEW_OWN, PERMISSIONS.TICKET_VIEW_ALL, PERMISSIONS.TICKET_EDIT_OWN, PERMISSIONS.TICKET_STATUS_CHANGE, PERMISSIONS.TICKET_ASSIGN, PERMISSIONS.TICKET_REASSIGN, PERMISSIONS.TICKET_ESCALATE, PERMISSIONS.COMMENT_PUBLIC, PERMISSIONS.COMMENT_INTERNAL, PERMISSIONS.ATTACHMENT_UPLOAD, PERMISSIONS.SLA_MANAGE, PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.REPORT_VIEW, PERMISSIONS.KNOWLEDGE_MANAGE, ...CRM_SUPERVISOR],
  AGENT: [PERMISSIONS.LOGIN, PERMISSIONS.TICKET_CREATE, PERMISSIONS.TICKET_VIEW_OWN, PERMISSIONS.TICKET_STATUS_CHANGE, PERMISSIONS.TICKET_ESCALATE, PERMISSIONS.COMMENT_PUBLIC, PERMISSIONS.COMMENT_INTERNAL, PERMISSIONS.ATTACHMENT_UPLOAD, PERMISSIONS.DASHBOARD_VIEW_LIMITED, PERMISSIONS.REPORT_VIEW_LIMITED, PERMISSIONS.KNOWLEDGE_MANAGE, PERMISSIONS.CRM_CLIENT_VIEW],
  CLIENT: [...PORTAL],
  REQUESTER: [...PORTAL],
} as const
