import type { UserRole } from '@/types/user.types'
import { PERMISSIONS } from '@/types/permission.types'

export const ROLES: Record<UserRole, string> = {
  ADMIN: 'Administrador',
  SALES: 'Ejecutivo comercial',
  SUPERVISOR: 'Supervisor',
  AGENT: 'Agente de soporte',
  CLIENT: 'Cliente portal',
  REQUESTER: 'Solicitante',
}

export const ASSIGNABLE_ROLES: UserRole[] = ['ADMIN', 'SUPERVISOR', 'AGENT', 'REQUESTER']

const CRM_SALES = [
  PERMISSIONS.CRM_CLIENT_VIEW, PERMISSIONS.CRM_CLIENT_CREATE, PERMISSIONS.CRM_CLIENT_EDIT,
  PERMISSIONS.CRM_CONTACT_VIEW, PERMISSIONS.CRM_CONTACT_CREATE, PERMISSIONS.CRM_CONTACT_EDIT,
  PERMISSIONS.CRM_OPPORTUNITY_VIEW, PERMISSIONS.CRM_OPPORTUNITY_CREATE, PERMISSIONS.CRM_OPPORTUNITY_EDIT, PERMISSIONS.CRM_OPPORTUNITY_MOVE,
  PERMISSIONS.CRM_ACTIVITY_VIEW, PERMISSIONS.CRM_ACTIVITY_CREATE, PERMISSIONS.CRM_ACTIVITY_EDIT,
  PERMISSIONS.CRM_SURVEY_VIEW, PERMISSIONS.CRM_SURVEY_MANAGE, PERMISSIONS.CRM_SURVEY_RESULTS,
  PERMISSIONS.CRM_DASHBOARD, PERMISSIONS.CRM_EXPORT, PERMISSIONS.CRM_RESPONSE_VIEW,
]

const CRM_SUPERVISOR = [
  PERMISSIONS.CRM_CLIENT_VIEW, PERMISSIONS.CRM_CONTACT_VIEW, PERMISSIONS.CRM_OPPORTUNITY_VIEW, PERMISSIONS.CRM_ACTIVITY_VIEW,
  PERMISSIONS.CRM_SURVEY_VIEW, PERMISSIONS.CRM_SURVEY_RESULTS, PERMISSIONS.CRM_DASHBOARD, PERMISSIONS.CRM_EXPORT, PERMISSIONS.CRM_RESPONSE_VIEW,
]

const PORTAL = [
  PERMISSIONS.LOGIN, PERMISSIONS.TICKET_CREATE, PERMISSIONS.TICKET_VIEW_OWN, PERMISSIONS.TICKET_EDIT_OWN,
  PERMISSIONS.COMMENT_PUBLIC, PERMISSIONS.ATTACHMENT_UPLOAD, PERMISSIONS.SURVEY_RESPOND,
]

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  ADMIN: Object.values(PERMISSIONS),
  SALES: [PERMISSIONS.LOGIN, ...CRM_SALES],
  SUPERVISOR: [
    PERMISSIONS.LOGIN, PERMISSIONS.TICKET_CREATE, PERMISSIONS.TICKET_VIEW_OWN, PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_EDIT_OWN, PERMISSIONS.TICKET_STATUS_CHANGE, PERMISSIONS.TICKET_ASSIGN, PERMISSIONS.TICKET_REASSIGN,
    PERMISSIONS.TICKET_ESCALATE, PERMISSIONS.COMMENT_PUBLIC, PERMISSIONS.COMMENT_INTERNAL, PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.SLA_MANAGE, PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.REPORT_VIEW, PERMISSIONS.KNOWLEDGE_MANAGE, ...CRM_SUPERVISOR,
  ],
  AGENT: [
    PERMISSIONS.LOGIN, PERMISSIONS.TICKET_CREATE, PERMISSIONS.TICKET_VIEW_OWN, PERMISSIONS.TICKET_STATUS_CHANGE,
    PERMISSIONS.TICKET_ESCALATE, PERMISSIONS.COMMENT_PUBLIC, PERMISSIONS.COMMENT_INTERNAL, PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.DASHBOARD_VIEW_LIMITED, PERMISSIONS.REPORT_VIEW_LIMITED, PERMISSIONS.KNOWLEDGE_MANAGE, PERMISSIONS.CRM_CLIENT_VIEW,
  ],
  CLIENT: [...PORTAL],
  REQUESTER: [...PORTAL],
}

export const ROUTE_PERMISSIONS: Record<string, string[]> = {
  '/dashboard': [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DASHBOARD_VIEW_LIMITED],
  '/tickets': [PERMISSIONS.TICKET_VIEW_OWN, PERMISSIONS.TICKET_VIEW_ALL],
  '/tickets/create': [PERMISSIONS.TICKET_CREATE],
  '/catalogs': [PERMISSIONS.CATEGORY_MANAGE, PERMISSIONS.PRIORITY_MANAGE, PERMISSIONS.SLA_MANAGE],
  '/users': [PERMISSIONS.USER_MANAGE],
  '/reports': [PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_VIEW_LIMITED],
  '/crm': [PERMISSIONS.CRM_CLIENT_VIEW, PERMISSIONS.CRM_DASHBOARD],
  '/crm/dashboard': [PERMISSIONS.CRM_DASHBOARD],
  '/crm/clients': [PERMISSIONS.CRM_CLIENT_VIEW],
  '/crm/contacts': [PERMISSIONS.CRM_CONTACT_VIEW],
  '/crm/opportunities': [PERMISSIONS.CRM_OPPORTUNITY_VIEW],
  '/crm/activities': [PERMISSIONS.CRM_ACTIVITY_VIEW],
  '/crm/surveys': [PERMISSIONS.CRM_SURVEY_VIEW],
  '/knowledge': [PERMISSIONS.KNOWLEDGE_MANAGE, PERMISSIONS.TICKET_VIEW_OWN],
}

export function isPortalRole(role: UserRole) {
  return role === 'CLIENT' || role === 'REQUESTER'
}
